// src/lib/fleet.ts
import { Car } from '@/types';

//
// ВАЖНО: Убедитесь, что ID здесь соответствуют ID в вашей таблице `prices`
//
export const fleet: Car[] = [
  { id: 1,  name: 'Mercedes-Benz G63 800',   slug: 'mercedes-benz-g63-800',   brand: 'Mercedes', class: 'Luxury',   price_per_day: 380000, image_url: '/cars/g63.jpg',    description: 'Абсолютная роскошь, мощь и комфорт.', power: 800, acceleration: 3.9, fuel_type: 'Бензин', drive_type: 'Полный', seats: 5, year: 2023 },
  { id: 2,  name: 'Mercedes-Benz W223 S580', slug: 'mercedes-benz-w223-s580', brand: 'Mercedes', class: 'Luxury',   price_per_day: 380000, image_url: '/cars/w223.jpg',    description: 'Флагманский седан для больших поездок.', power: 503, acceleration: 4.4, fuel_type: 'Бензин', drive_type: 'Полный', seats: 5, year: 2022 },
  { id: 3,  name: 'Lexus LX 570 2017',       slug: 'lexus-lx570-2017',       brand: 'Lexus',    class: 'Luxury',   price_per_day: 150000, image_url: '/cars/lx570.jpg',    description: 'Легендарный внедорожник — стиль и сила.', power: 367, acceleration: 7.7, fuel_type: 'Бензин', drive_type: 'Полный', seats: 7, year: 2017 },
  { id: 4,  name: 'Toyota LC200',            slug: 'toyota-lc200',            brand: 'Toyota',   class: 'Luxury',   price_per_day: 150000, image_url: '/cars/lc200.jpg',    description: 'Надёжность и комфорт бизнес-класса.', power: 309, acceleration: 8.6, fuel_type: 'Бензин', drive_type: 'Полный', seats: 7, year: 2021 },
  { id: 5,  name: 'BMW 428i Cabrio',         slug: 'bmw-428i-cabrio',         brand: 'BMW',      class: 'Premium',  price_per_day: 100000, image_url: '/cars/bmw428.jpg',   description: 'Свобода и скорость в элегантном кабриолете.', power: 245, acceleration: 6.4, fuel_type: 'Бензин', drive_type: 'Задний', seats: 4, year: 2016 },
  { id: 11, name: 'Mercedes-Benz E-class',   slug: 'mercedes-benz-e-class',   brand: 'Mercedes', class: 'Business', price_per_day: 80000,  image_url: '/cars/e-class.jpg', description: 'Идеальный баланс комфорта и технологий.', power: 197, acceleration: 7.6, fuel_type: 'Бензин', drive_type: 'Задний', seats: 5, year: 2020 },
  { id: 13, name: 'Rolls Royce Ghost',       slug: 'rolls-royce-ghost',       brand: 'Rolls Royce', class: 'Luxury', price_per_day: 400000, image_url: '/cars/ghost.jpg', description: 'Непревзойденная роскошь и умиротворение.', power: 571, acceleration: 4.8, fuel_type: 'Бензин', drive_type: 'Полный', seats: 5, year: 2021 },
  { id: 14, name: 'BMW X5',                  slug: 'bmw-x5',                  brand: 'BMW',      class: 'Premium',  price_per_day: 200000, image_url: '/cars/x5.jpg',     description: 'Сочетание динамики и универсальности.', power: 340, acceleration: 5.5, fuel_type: 'Бензин', drive_type: 'Полный', seats: 5, year: 2022 },
  { id: 15, name: 'Zeekr001',                slug: 'zeekr-001',               brand: 'Zeekr',    class: 'Premium',  price_per_day: 100000, image_url: '/cars/zeekr001.jpg', description: 'Электрический спорткар будущего.', power: 544, acceleration: 3.8, fuel_type: 'Электро', drive_type: 'Полный', seats: 5, year: 2023 },
  { id: 16, name: 'Zeekr007',                slug: 'zeekr-007',               brand: 'Zeekr',    class: 'Premium',  price_per_day: 100000, image_url: '/cars/zeekr007.jpg', description: 'Инновации и дизайн в каждой детали.', power: 646, acceleration: 3.8, fuel_type: 'Электро', drive_type: 'Полный', seats: 5, year: 2024 },
];