create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.slugify(input text)
returns text
language sql
immutable
as $$
    select trim(both '-' from regexp_replace(lower(coalesce(input, '')), '[^a-z0-9]+', '-', 'g'));
$$;

create table if not exists public.admin_users (
    id bigint generated by default as identity primary key,
    email text not null unique,
    created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.admin_users
        where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    );
$$;

create table if not exists public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null unique,
    full_name text,
    phone text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.users enable row level security;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

create or replace function public.handle_auth_user_sync()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.users (id, email, full_name, phone)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name'),
        new.raw_user_meta_data ->> 'phone'
    )
    on conflict (id) do update
    set
        email = excluded.email,
        full_name = coalesce(excluded.full_name, public.users.full_name),
        phone = coalesce(excluded.phone, public.users.phone),
        updated_at = now();

    return new;
end;
$$;

drop trigger if exists on_auth_user_sync on auth.users;
create trigger on_auth_user_sync
after insert or update on auth.users
for each row
execute function public.handle_auth_user_sync();

insert into public.users (id, email, full_name, phone)
select
    id,
    email,
    coalesce(raw_user_meta_data ->> 'name', raw_user_meta_data ->> 'full_name'),
    raw_user_meta_data ->> 'phone'
from auth.users
on conflict (id) do update
set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.users.full_name),
    phone = coalesce(excluded.phone, public.users.phone),
    updated_at = now();

drop policy if exists "users_select_own" on public.users;
create policy "users_select_own"
on public.users
for select
to authenticated
using (auth.uid() = id or public.is_admin());

drop policy if exists "users_update_own" on public.users;
create policy "users_update_own"
on public.users
for update
to authenticated
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

create table if not exists public.cars (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    brand text not null,
    class text not null check (
        class in (
            'Economy',
            'Business',
            'Premium',
            'Luxury',
            'Эконом',
            'Бизнес',
            'Премиум',
            'Люкс'
        )
    ),
    description text not null default '',
    full_description text,
    image_url text not null default '',
    gallery_images text[] not null default '{}',
    price integer not null default 0,
    price_per_day integer not null default 0,
    power integer,
    acceleration numeric(4, 1),
    fuel_type text,
    drive_type text,
    seats integer,
    year integer,
    is_available boolean not null default true,
    available boolean,
    status text not null default 'available',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.cars enable row level security;

create index if not exists cars_slug_idx on public.cars (slug);
create index if not exists cars_brand_idx on public.cars (brand);
create index if not exists cars_class_idx on public.cars (class);
create index if not exists cars_status_idx on public.cars (status);

create or replace function public.normalize_car_fields()
returns trigger
language plpgsql
as $$
begin
    if new.slug is null or btrim(new.slug) = '' then
        new.slug = public.slugify(new.name);
    else
        new.slug = public.slugify(new.slug);
    end if;

    if coalesce(new.price_per_day, 0) = 0 and coalesce(new.price, 0) > 0 then
        new.price_per_day = new.price;
    end if;

    if coalesce(new.price, 0) = 0 and coalesce(new.price_per_day, 0) > 0 then
        new.price = new.price_per_day;
    end if;

    if new.available is null then
        new.available = new.is_available;
    end if;

    if coalesce(new.status, '') = '' then
        new.status = case when coalesce(new.available, true) then 'available' else 'unavailable' end;
    end if;

    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists normalize_car_fields on public.cars;
create trigger normalize_car_fields
before insert or update on public.cars
for each row
execute function public.normalize_car_fields();

drop policy if exists "cars_select_public" on public.cars;
create policy "cars_select_public"
on public.cars
for select
to anon, authenticated
using (true);

drop policy if exists "cars_manage_admin" on public.cars;
create policy "cars_manage_admin"
on public.cars
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create table if not exists public.prices (
    id bigint generated by default as identity primary key,
    car_id bigint not null references public.cars(id) on delete cascade,
    days_from integer not null,
    days_to integer not null,
    price_per_day integer not null,
    with_driver boolean not null default false,
    duration_unit text not null default 'day'
        check (duration_unit in ('day', 'hour')),
    conditions text,
    created_at timestamptz not null default now(),
    constraint prices_days_check check (days_from > 0 and days_to >= days_from),
    constraint prices_unique_range unique (car_id, days_from, days_to, with_driver, duration_unit)
);

alter table public.prices enable row level security;

create index if not exists prices_car_id_idx on public.prices (car_id);
create index if not exists prices_car_id_duration_unit_idx on public.prices (car_id, duration_unit, with_driver);

drop policy if exists "prices_select_public" on public.prices;
create policy "prices_select_public"
on public.prices
for select
to anon, authenticated
using (true);

drop policy if exists "prices_manage_admin" on public.prices;
create policy "prices_manage_admin"
on public.prices
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create table if not exists public.saved_calculations (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    car_name text not null,
    service_type text not null,
    duration text not null,
    price integer not null default 0,
    created_at timestamptz not null default now()
);

alter table public.saved_calculations enable row level security;

create index if not exists saved_calculations_user_id_idx on public.saved_calculations (user_id);

drop policy if exists "saved_calculations_select_own" on public.saved_calculations;
create policy "saved_calculations_select_own"
on public.saved_calculations
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "saved_calculations_insert_own" on public.saved_calculations;
create policy "saved_calculations_insert_own"
on public.saved_calculations
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "saved_calculations_delete_own" on public.saved_calculations;
create policy "saved_calculations_delete_own"
on public.saved_calculations
for delete
to authenticated
using (auth.uid() = user_id or public.is_admin());

create table if not exists public.bookings (
    id uuid primary key default gen_random_uuid(),
    car_id bigint references public.cars(id) on delete set null,
    user_id uuid references auth.users(id) on delete set null,
    car_name text not null,
    car_image_url text,
    user_name text,
    user_phone text not null,
    date_from date not null,
    date_to date not null,
    duration_unit text not null default 'day'
        check (duration_unit in ('day', 'hour')),
    duration_value integer
        check (duration_value is null or duration_value > 0),
    total_price integer not null default 0,
    status text not null default 'confirmed'
        check (status in ('pending', 'confirmed', 'active', 'completed', 'cancelled')),
    created_at timestamptz not null default now(),
    constraint bookings_date_check check (date_to >= date_from)
);

alter table public.bookings enable row level security;

create index if not exists bookings_user_id_idx on public.bookings (user_id);
create index if not exists bookings_car_id_idx on public.bookings (car_id);
create index if not exists bookings_date_from_idx on public.bookings (date_from);

drop policy if exists "bookings_select_admin" on public.bookings;
create policy "bookings_select_admin"
on public.bookings
for select
to authenticated
using (public.is_admin());

drop policy if exists "bookings_manage_admin" on public.bookings;
create policy "bookings_manage_admin"
on public.bookings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create table if not exists public.promocodes (
    id bigint generated by default as identity primary key,
    code text not null unique,
    discount_type text not null check (discount_type in ('percent', 'amount')),
    discount_value numeric(12, 2) not null,
    description text,
    expiry_date timestamptz,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.promocodes enable row level security;

create index if not exists promocodes_code_idx on public.promocodes (code);

drop policy if exists "promocodes_select_authenticated" on public.promocodes;
create policy "promocodes_select_authenticated"
on public.promocodes
for select
to authenticated
using (true);

drop policy if exists "promocodes_manage_admin" on public.promocodes;
create policy "promocodes_manage_admin"
on public.promocodes
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create table if not exists public.user_promo_codes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    promocode_id bigint not null references public.promocodes(id) on delete cascade,
    is_used boolean not null default false,
    created_at timestamptz not null default now(),
    constraint user_promo_codes_unique unique (user_id, promocode_id)
);

alter table public.user_promo_codes enable row level security;

create index if not exists user_promo_codes_user_id_idx on public.user_promo_codes (user_id);
create index if not exists user_promo_codes_promocode_id_idx on public.user_promo_codes (promocode_id);

drop policy if exists "user_promo_codes_select_own" on public.user_promo_codes;
create policy "user_promo_codes_select_own"
on public.user_promo_codes
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_promo_codes_manage_admin" on public.user_promo_codes;
create policy "user_promo_codes_manage_admin"
on public.user_promo_codes
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create table if not exists public.public_promocodes (
    id bigint generated by default as identity primary key,
    code text not null unique,
    is_active boolean not null default true,
    discount_perc integer not null check (discount_perc >= 0 and discount_perc <= 100),
    expires_at timestamptz not null default (now() + interval '1 year'),
    times_used integer not null default 0 check (times_used >= 0),
    usage_limit integer,
    is_personal boolean not null default false,
    user_id uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    constraint public_promocodes_usage_limit_check check (usage_limit is null or usage_limit >= 0)
);

alter table public.public_promocodes enable row level security;

create index if not exists public_promocodes_code_idx on public.public_promocodes (code);
create index if not exists public_promocodes_user_id_idx on public.public_promocodes (user_id);

drop policy if exists "public_promocodes_select_public" on public.public_promocodes;
create policy "public_promocodes_select_public"
on public.public_promocodes
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "public_promocodes_manage_admin" on public.public_promocodes;
create policy "public_promocodes_manage_admin"
on public.public_promocodes
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('cars', 'cars', true)
on conflict (id) do update
set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('company-documents', 'company-documents', false)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "cars_bucket_public_read" on storage.objects;
create policy "cars_bucket_public_read"
on storage.objects
for select
to public
using (bucket_id = 'cars');

drop policy if exists "cars_bucket_admin_insert" on storage.objects;
create policy "cars_bucket_admin_insert"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'cars' and public.is_admin());

drop policy if exists "cars_bucket_admin_update" on storage.objects;
create policy "cars_bucket_admin_update"
on storage.objects
for update
to authenticated
using (bucket_id = 'cars' and public.is_admin())
with check (bucket_id = 'cars' and public.is_admin());

drop policy if exists "cars_bucket_admin_delete" on storage.objects;
create policy "cars_bucket_admin_delete"
on storage.objects
for delete
to authenticated
using (bucket_id = 'cars' and public.is_admin());

comment on table public.admin_users is 'Emails allowed to manage admin-protected resources.';
comment on table public.users is 'Public user profiles synced from auth.users.';
comment on table public.cars is 'Primary vehicle catalog used by the fleet, calculator and detail pages.';
comment on table public.prices is 'Rental price tiers linked to cars.';
comment on table public.saved_calculations is 'Saved calculator results for authenticated users.';
comment on table public.bookings is 'Operational booking registry used by the admin bookings page.';
comment on table public.promocodes is 'Personal promo codes used in the dashboard.';
comment on table public.public_promocodes is 'Public promo codes validated from calculator and booking flows.';
